export const GENERATE_OTP_REQUEST= 'GENERATE_OTP_REQUEST';
export const GENERATE_OTP_SUCCESS= 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILURE= 'GENERATE_OTP_FAILURE';

export const VERIFY_OTP_REQUEST= 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS= 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE= 'VERIFY_OTP_FAILURE';

export const GET_USER_REQUEST= 'GET_USER_REQUEST';
export const GET_USER_SUCCESS= 'GET_USER_SUCCESS';
export const GET_USER_FAILURE= 'GET_USER_FAILURE';

